// The contract ABI is the interface between contracts, api and web (CLAUDE.md). Generating it
// from the compiled artifact means the backend cannot drift from the deployed bytecode — a
// hand-copied ABI can, silently, and the failure shows up as a decoded-garbage read.
//
//   pnpm --filter @roster/api abi:sync

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const artifacts = resolve(here, '../../../packages/contracts/out')
const target = resolve(here, '../src/chain/abi.ts')

const load = (name) => {
  const path = resolve(artifacts, `${name}.sol/${name}.json`)
  try {
    return JSON.parse(readFileSync(path, 'utf8')).abi
  } catch {
    throw new Error(`No artifact at ${path}. Run \`pnpm contracts:build\` first.`)
  }
}

const roster = load('Roster')
const factory = load('RosterFactory')

const banner = `// GENERATED by scripts/sync-abi.mjs from packages/contracts/out — do not edit by hand.
// Re-run \`pnpm --filter @roster/api abi:sync\` after any contract change.
`

mkdirSync(dirname(target), { recursive: true })
writeFileSync(
  target,
  `${banner}
export const rosterAbi = ${JSON.stringify(roster, null, 2)} as const

export const rosterFactoryAbi = ${JSON.stringify(factory, null, 2)} as const
`,
)

console.log(`wrote ${target} — ${roster.length} Roster entries, ${factory.length} RosterFactory entries`)
